<?php

namespace NEWS\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
  public function findAllOrderedByTimesViewed(){

      $results = $this->getEntityManager()
          ->createQuery(
          'SELECT p FROM NEWSBlogBundle:Post p ORDER BY p.numberOfTimesViewed ASC'
      )
          ->getResult();

    return $results;
  }

    /////Search
    public function searchPost( $title ){
        $qb = $this->createQueryBuilder('f');
        $qb->where( 'f.title LIKE :title' )
            ->setParameter( 'title', '%'. $title .'%' );

        return $qb->getQuery()->getResult();
    }


}
