parameters:
#    news_blog.example.class: NEWS\BlogBundle\Example

services:
#    news_blog.example:
#        class: %news_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
